"""add unique paid payment constraint

Revision ID: 0c1fdda8ff73
Revises: 26b4bb3a9530
Create Date: 2026-10-09 15:01:22.012535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1fdda8ff73'
down_revision: Union[str, Sequence[str], None] = '26b4bb3a9530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_paid_payment_per_booking', 'payments', ['booking_id'], unique=True, sqlite_where=sa.text("status = 'PAID'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_paid_payment_per_booking', table_name='payments', sqlite_where=sa.text("status = 'PAID'"))
    # ### end Alembic commands ###
